server:
  port: 8888
spring:
  application:
    name: experiment-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/hecenjie/Projects/experiment-config
  security:
    user:
      name: hecenjie
      password: 980704
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
